services:
  - type: web
    name: cinerusubs-web
    runtime: node
    plan: standard
    buildCommand: npm ci && npm run build
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4001
      - key: NEXT_PUBLIC_SITE_URL
        sync: false
      - key: NEXT_PUBLIC_SITE_NAME
        value: CineruSubs
      - key: CINERUSUBS_DEMO_MODE
        value: false
      - key: MONGODB_URI
        sync: false
      - key: MONGODB_DB
        value: cinerusubs
      - key: SESSION_SECRET
        generateValue: true
      - key: DOWNLOAD_SIGNING_SECRET
        generateValue: true
      - key: R2_ACCOUNT_ID
        sync: false
      - key: R2_ACCESS_KEY_ID
        sync: false
      - key: R2_SECRET_ACCESS_KEY
        sync: false
      - key: R2_ENDPOINT
        sync: false
      - key: R2_MEDIA_BUCKET
        value: cinerusubs-media
      - key: R2_ASSETS_BUCKET
        value: cinerusubs-assets
      - key: PUBLIC_ASSET_DOMAIN
        value: https://assets.cinerusubs.com
      - key: DOWNLOAD_DOMAIN
        value: https://dl.cinerusubs.com
      - key: DOWNLOAD_WORKER_ENABLED
        value: false
      - key: TMDB_API_TOKEN
        sync: false
      - key: TURNSTILE_SECRET_KEY
        sync: false
