import type { Metadata } from 'next';
import { BadgeCheck, CalendarDays, Star } from 'lucide-react';
import Image from 'next/image';
import { notFound } from 'next/navigation';
import { SubtitleCard } from '@/components/subtitle/subtitle-card';
import { getTranslatorBySlug, getTranslatorSubtitles } from '@/services/catalog';

export const dynamic='force-dynamic';
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const t=await getTranslatorBySlug(slug);return t?{title:`${t.displayName} — Subtitle Translator`,description:t.bio}:{};}
export default async function TranslatorPage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const translator=await getTranslatorBySlug(slug);if(!translator)notFound();const subtitles=await getTranslatorSubtitles(translator.id);const schema={'@context':'https://schema.org','@type':'Person',name:translator.displayName,description:translator.bio};return <><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/><div className="page-shell translator-page"><header className="translator-hero">{translator.avatarUrl&&<span><Image src={translator.avatarUrl} alt={`${translator.displayName} profile`} fill sizes="120px"/></span>}<div><div className="verified-name"><h1>{translator.displayName}</h1>{translator.verified&&<BadgeCheck/>}</div><p>{translator.bio}</p><div className="translator-stats"><span><b>{translator.totalSubtitles}</b>Subtitles</span><span><b>{translator.totalDownloads.toLocaleString()}</b>Downloads</span><span><b><Star/>{translator.averageRating.toFixed(1)}</b>Average rating</span><span><b><CalendarDays/>{new Date(translator.joinedAt).toLocaleDateString('en-LK',{month:'short',year:'numeric'})}</b>Joined</span></div></div></header><section className="translator-releases"><header><span className="section-label">Contribution history</span><h2>Recent subtitles</h2></header><div className="subtitle-list">{subtitles.map(item=><SubtitleCard key={item.id} subtitle={item}/>)}</div></section></div></>}
