import { isValidObjectId } from 'mongoose';
import { z } from 'zod';
import { assertMutationRequest, requirePermission } from '@/lib/auth';
import { connectDb } from '@/lib/db';
import { apiError } from '@/lib/http';
import { assertMediaDistributionAllowed } from '@/lib/rights';
import { AuditLog, Episode, MediaAsset, MediaVersion, Movie } from '@/models';
import { RIGHTS_STATUSES, type RightsStatus } from '@/types/content';

const schema=z.object({assetId:z.string(),contentId:z.string(),contentType:z.enum(['movie','episode']),quality:z.string().max(40),resolution:z.string().max(40),codec:z.string().max(40).optional(),container:z.string().max(40).optional(),audioCodec:z.string().max(40).optional(),audioLanguages:z.array(z.string()).max(20).default([]),subtitleLanguages:z.array(z.string()).max(20).default([]),releaseType:z.string().max(80).optional(),rightsStatus:z.enum(RIGHTS_STATUSES),regionRestrictions:z.array(z.string()).max(250).default([]),active:z.boolean().default(false)});
export async function POST(request:Request){try{const session=await requirePermission('media.update');await assertMutationRequest(request,session);const input=schema.parse(await request.json());if(!isValidObjectId(input.assetId)||!isValidObjectId(input.contentId))throw Object.assign(new Error('Asset or content record was not found.'),{status:404,code:'NOT_FOUND'});await connectDb();const [asset,content]=await Promise.all([MediaAsset.findOne({_id:input.assetId,kind:'media',status:'active'}),input.contentType==='movie'?Movie.findById(input.contentId):Episode.findById(input.contentId)]);if(!asset||!content)throw Object.assign(new Error('Active media asset or content record was not found.'),{status:404,code:'NOT_FOUND'});if(input.active){assertMediaDistributionAllowed(content.rightsStatus as RightsStatus,true);assertMediaDistributionAllowed(input.rightsStatus,true);}const version=await MediaVersion.create({...input,r2ObjectKey:asset.objectKey,fileSize:asset.size,createdBy:session.user.id});asset.linkedModel=input.contentType==='movie'?'Movie':'Episode';asset.linkedId=input.contentId;await asset.save();await AuditLog.create({actor:session.user.id,action:'media_version.create',entity:'MediaVersion',entityId:String(version._id),metadata:{contentId:input.contentId,active:input.active,rightsStatus:input.rightsStatus}});return Response.json({id:String(version._id)},{status:201});}catch(error){return apiError(error);}}
