import { isValidObjectId } from 'mongoose';
import { assertMutationRequest, requirePermission } from '@/lib/auth';
import { connectDb } from '@/lib/db';
import { apiError } from '@/lib/http';
import { assertMediaDistributionAllowed } from '@/lib/rights';
import { AuditLog, Episode, MediaAsset, MediaVersion, Movie } from '@/models';
import type { RightsStatus } from '@/types/content';
import { mediaVersionInputSchema } from '@/lib/validation/media';

export async function POST(request:Request){try{const session=await requirePermission('media.update');await assertMutationRequest(request,session);const input=mediaVersionInputSchema.parse(await request.json());if(!isValidObjectId(input.assetId)||!isValidObjectId(input.contentId))throw Object.assign(new Error('Asset or content record was not found.'),{status:404,code:'NOT_FOUND'});await connectDb();const [asset,content]=await Promise.all([MediaAsset.findOne({_id:input.assetId,kind:'media',status:'active'}),input.contentType==='movie'?Movie.findById(input.contentId):Episode.findById(input.contentId)]);if(!asset||!content)throw Object.assign(new Error('Active media asset or content record was not found.'),{status:404,code:'NOT_FOUND'});if(input.active){assertMediaDistributionAllowed(content.rightsStatus as RightsStatus,true);assertMediaDistributionAllowed(input.rightsStatus,true);}const version=await MediaVersion.create({...input,r2ObjectKey:asset.objectKey,storageBucket:asset.bucket,fileName:asset.fileName,fileSize:asset.size,createdBy:session.user.id,updatedBy:session.user.id});asset.linkedModel=input.contentType==='movie'?'Movie':'Episode';asset.linkedId=input.contentId;await asset.save();await AuditLog.create({actor:session.user.id,action:'media_version.create',entity:'MediaVersion',entityId:String(version._id),metadata:{contentId:input.contentId,active:input.active,rightsStatus:input.rightsStatus,quality:input.quality,releaseType:input.releaseType}});return Response.json({id:String(version._id)},{status:201});}catch(error){return apiError(error);}}
