import type { Metadata } from 'next';
import { Star } from 'lucide-react';
import Image from 'next/image';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import { WatchlistButton } from '@/components/movie/watchlist-button';
import { SeasonBrowser } from '@/components/tv/season-browser';
import { rightsLabel } from '@/lib/rights';
import { siteUrl } from '@/lib/env';
import { getSeriesBySlug } from '@/services/catalog';

export const dynamic = 'force-dynamic';
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const series=await getSeriesBySlug(slug);return series?{title:`${series.title} — TV Series`,description:series.overview,alternates:{canonical:`/tv/${series.slug}`},openGraph:{title:series.title,description:series.overview,images:[series.backdropUrl]}}:{}}
export default async function SeriesPage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const series=await getSeriesBySlug(slug);if(!series)notFound();const episodeCount=series.seasons.reduce((sum,item)=>sum+item.episodes.length,0);const schema={'@context':'https://schema.org','@type':'TVSeries',name:series.title,description:series.overview,image:`${siteUrl}${series.posterUrl}`,numberOfSeasons:series.seasons.length,numberOfEpisodes:episodeCount,genre:series.genres};return <><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema).replaceAll('<','\\u003c')}}/><article className="series-page"><header className="series-hero"><div className="detail-backdrop"><Image src={series.backdropUrl} alt="" fill priority sizes="100vw"/></div><div className="series-hero-inner"><div className="detail-poster"><Image src={series.posterUrl} alt={`${series.title} poster`} fill priority sizes="250px"/></div><div><nav aria-label="Breadcrumb"><Link href="/">Home</Link><span>/</span><Link href="/tv">TV Series</Link><span>/</span><span>{series.title}</span></nav><span className="detail-kicker">{series.genres.join(' · ')}</span><h1>{series.title}</h1>{series.sinhalaTitle&&<p className="sinhala-title" lang="si">{series.sinhalaTitle}</p>}<div className="detail-meta"><span>{series.year}</span><i/><span>{series.seasons.length} season{series.seasons.length===1?'':'s'}</span><i/><span>{episodeCount} episodes</span><i/><span>{series.status}</span></div>{series.tmdbRating&&<div className="rating-row"><span><b>Rating</b><strong><Star/>{series.tmdbRating.toFixed(1)}</strong></span><span className={`rights-chip rights-${series.rightsStatus}`}>{rightsLabel(series.rightsStatus)}</span></div>}<p className="detail-overview">{series.overview}</p><div className="detail-secondary"><WatchlistButton id={series.id} type="series" slug={series.slug} title={series.title} posterUrl={series.posterUrl} label/></div></div></div></header><div className="series-content"><header><span className="section-label">Episode guide</span><h2>Seasons & Episodes</h2></header><SeasonBrowser seriesSlug={series.slug} seasons={series.seasons}/></div></article></>}
