import type { Metadata } from 'next';
import { CalendarDays, Clock3, Languages } from 'lucide-react';
import Image from 'next/image';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import { rightsLabel } from '@/lib/rights';
import { getSeriesBySlug } from '@/services/catalog';

export const dynamic='force-dynamic';
export async function generateMetadata({params}:{params:Promise<{slug:string;season:string;episode:string}>}):Promise<Metadata>{const p=await params;const s=await getSeriesBySlug(p.slug);const e=s?.seasons.find(x=>x.seasonNumber===Number(p.season))?.episodes.find(x=>x.episodeNumber===Number(p.episode));return e&&s?{title:`${s.title}: ${e.title}`,description:e.overview}:{};}
export default async function EpisodePage({params}:{params:Promise<{slug:string;season:string;episode:string}>}){const p=await params;const series=await getSeriesBySlug(p.slug);const season=series?.seasons.find(item=>item.seasonNumber===Number(p.season));const episode=season?.episodes.find(item=>item.episodeNumber===Number(p.episode));if(!series||!season||!episode)notFound();return <article className="episode-page"><header><div><Image src={episode.thumbnailUrl} alt="" fill priority sizes="100vw"/></div><section><nav><Link href="/tv">TV Series</Link><span>/</span><Link href={`/tv/${series.slug}`}>{series.title}</Link></nav><span className="detail-kicker">Season {season.seasonNumber} · Episode {episode.episodeNumber}</span><h1>{episode.title}</h1><p>{episode.overview}</p><div className="episode-meta"><span><Clock3/>{episode.runtime} min</span><span><CalendarDays/>{new Date(episode.releaseDate).toLocaleDateString('en-LK',{day:'numeric',month:'long',year:'numeric'})}</span><span><Languages/>{episode.subtitleLanguages.join(', ')} subtitles</span></div><span className={`rights-chip rights-${episode.rightsStatus}`}>{rightsLabel(episode.rightsStatus)}</span></section></header><div className="episode-body"><h2>Episode access</h2><p>Media playback is enabled only when an active authorized version is attached. Subtitle files remain independently available from the episode’s series page.</p><Link className="action-button secondary" href={`/tv/${series.slug}`}>Back to episode guide</Link></div></article>}
