import { isValidObjectId, Types } from 'mongoose';
import { z } from 'zod';
import { assertMutationRequest, currentSession } from '@/lib/auth';
import { connectDb } from '@/lib/db';
import { useDemoData } from '@/lib/env';
import { apiError } from '@/lib/http';
import { enforceRateLimit } from '@/lib/rate-limit';
import { Comment, CommentLike, Movie, Rating, Report, Series, Subtitle, User } from '@/models';

const targetTypes=['movie','series','subtitle'] as const;const mutation=z.discriminatedUnion('action',[z.object({action:z.literal('comment'),body:z.string().trim().min(2).max(2000),parentId:z.string().optional()}),z.object({action:z.literal('rating'),value:z.number().int().min(1).max(10)}),z.object({action:z.literal('report'),reason:z.string().trim().min(3).max(120),details:z.string().trim().max(1000).optional()}),z.object({action:z.literal('like'),commentId:z.string()}),z.object({action:z.literal('edit'),commentId:z.string(),body:z.string().trim().min(2).max(2000)}),z.object({action:z.literal('delete'),commentId:z.string()})]);
export async function GET(_request:Request,{params}:RouteContext<'/api/community/[type]/[id]'>){try{const{type,id}=await params;const targetType=z.enum(targetTypes).parse(type);if(useDemoData)return Response.json({comments:[],averageRating:null,ratingCount:0,userRating:null});if(!isValidObjectId(id))throw Object.assign(new Error('Content was not found.'),{status:404,code:'NOT_FOUND'});await connectDb();const session=await currentSession();const[comments,ratings,userRating]=await Promise.all([Comment.find({targetType,targetId:id,status:'visible'}).sort({createdAt:1}).limit(100).lean(),Rating.aggregate([{$match:{targetType,targetId:new Types.ObjectId(id)}},{$group:{_id:null,average:{$avg:'$value'},count:{$sum:1}}}]),session?Rating.findOne({user:session.user.id,targetType,targetId:id}).lean():null]);const userIds=[...new Set(comments.map((item)=>String(item.user)))];const users=await User.find({_id:{$in:userIds}}).select('displayName name').lean();const names=new Map(users.map((user)=>[String(user._id),String(user.displayName||user.name)]));const liked=session?new Set((await CommentLike.find({user:session.user.id,comment:{$in:comments.map(item=>item._id)}}).select('comment').lean()).map(item=>String(item.comment))):new Set<string>();return Response.json({comments:comments.map((item)=>({id:String(item._id),parentId:item.parent?String(item.parent):undefined,body:String(item.body),author:names.get(String(item.user))||'CineSeya.lk member',createdAt:new Date(item.createdAt as Date).toISOString(),editedAt:item.editedAt?new Date(item.editedAt as Date).toISOString():undefined,likeCount:Number(item.likeCount||0),owned:String(item.user)===session?.user.id,liked:liked.has(String(item._id))})),averageRating:ratings[0]?.average??null,ratingCount:ratings[0]?.count??0,userRating:userRating?.value??null},{headers:{'Cache-Control':'private, no-store'}});}catch(error){return apiError(error);}}
export async function POST(request:Request,{params}:RouteContext<'/api/community/[type]/[id]'>){try{await enforceRateLimit(request,'community-write',30,10*60_000);const session=await currentSession();if(!session)throw Object.assign(new Error('Authentication is required.'),{status:401,code:'AUTH_REQUIRED'});await assertMutationRequest(request,session);const{type,id}=await params;const targetType=z.enum(targetTypes).parse(type);if(!isValidObjectId(id))throw Object.assign(new Error('Content was not found.'),{status:404,code:'NOT_FOUND'});const input=mutation.parse(await request.json());await connectDb();const model=targetType==='movie'?Movie:targetType==='series'?Series:Subtitle;if(!await model.exists({_id:id}))throw Object.assign(new Error('Content was not found.'),{status:404,code:'NOT_FOUND'});if(input.action==='comment'){if(input.parentId&&(!isValidObjectId(input.parentId)||!await Comment.exists({_id:input.parentId,targetType,targetId:id,status:'visible'})))throw Object.assign(new Error('The comment being replied to was not found.'),{status:404,code:'COMMENT_NOT_FOUND'});const comment=await Comment.create({user:session.user.id,targetType,targetId:id,parent:input.parentId,body:input.body,status:'visible'});return Response.json({id:String(comment._id)},{status:201});}if(input.action==='rating'){await Rating.updateOne({user:session.user.id,targetType,targetId:id},{$set:{value:input.value}},{upsert:true});return Response.json({ok:true});}if(input.action==='report'){const report=await Report.create({reporter:session.user.id,targetType,targetId:id,reason:input.reason,details:input.details});return Response.json({id:String(report._id)},{status:201});}if(!isValidObjectId(input.commentId))throw Object.assign(new Error('Comment was not found.'),{status:404,code:'COMMENT_NOT_FOUND'});const comment=await Comment.findOne({_id:input.commentId,targetType,targetId:id,status:'visible'});if(!comment)throw Object.assign(new Error('Comment was not found.'),{status:404,code:'COMMENT_NOT_FOUND'});if(input.action==='edit'||input.action==='delete'){if(String(comment.user)!==session.user.id)throw Object.assign(new Error('You may change only your own comment.'),{status:403,code:'FORBIDDEN'});if(input.action==='edit'){comment.body=input.body;comment.editedAt=new Date();await comment.save();}else{comment.status='deleted';await comment.save();}return Response.json({ok:true});}const existing=await CommentLike.findOne({user:session.user.id,comment:comment._id});if(existing){await existing.deleteOne();await Comment.updateOne({_id:comment._id,likeCount:{$gt:0}},{$inc:{likeCount:-1}});return Response.json({liked:false});}await CommentLike.create({user:session.user.id,comment:comment._id});await Comment.updateOne({_id:comment._id},{$inc:{likeCount:1}});return Response.json({liked:true});}catch(error){return apiError(error);}}
