import { isValidObjectId } from 'mongoose';
import { adminMovieSchema } from '@/lib/validation/movie';
import { assertMutationRequest, requirePermission } from '@/lib/auth';
import { connectDb } from '@/lib/db';
import { apiError } from '@/lib/http';
import { AuditLog, Movie } from '@/models';

const validId=(id:string)=>{if(!isValidObjectId(id))throw Object.assign(new Error('Movie was not found.'),{status:404,code:'NOT_FOUND'});};
export async function GET(_request:Request,{params}:RouteContext<'/api/admin/movies/[id]'>){try{await requirePermission('content.read');const{id}=await params;validId(id);await connectDb();const movie=await Movie.findById(id).lean();if(!movie)throw Object.assign(new Error('Movie was not found.'),{status:404,code:'NOT_FOUND'});return Response.json({movie},{headers:{'Cache-Control':'private, no-store'}});}catch(error){return apiError(error);}}
export async function PATCH(request:Request,{params}:RouteContext<'/api/admin/movies/[id]'>){try{const session=await requirePermission('content.update');await assertMutationRequest(request,session);const{id}=await params;validId(id);const input=adminMovieSchema.parse(await request.json());if(input.publicationStatus==='published'&&!session.user.permissions.includes('content.publish'))throw Object.assign(new Error('Publishing permission is required.'),{status:403,code:'FORBIDDEN'});await connectDb();const prior=await Movie.findById(id);if(!prior)throw Object.assign(new Error('Movie was not found.'),{status:404,code:'NOT_FOUND'});const firstPublish=input.publicationStatus==='published'&&prior.publicationStatus!=='published';prior.set({...input,publishedAt:firstPublish?new Date():prior.publishedAt,updatedBy:session.user.id});await prior.save();await AuditLog.create({actor:session.user.id,action:'movie.update',entity:'Movie',entityId:id,metadata:{title:prior.title,publicationStatus:prior.publicationStatus,rightsStatus:prior.rightsStatus}});return Response.json({id,slug:prior.slug});}catch(error){if((error as {code?:number}).code===11000)return Response.json({error:{code:'SLUG_EXISTS',message:'That movie slug is already in use.'}},{status:409});return apiError(error);}}
export async function DELETE(request:Request,{params}:RouteContext<'/api/admin/movies/[id]'>){try{const session=await requirePermission('content.archive');await assertMutationRequest(request,session);const{id}=await params;validId(id);await connectDb();const movie=await Movie.findByIdAndUpdate(id,{publicationStatus:'archived',updatedBy:session.user.id},{new:true});if(!movie)throw Object.assign(new Error('Movie was not found.'),{status:404,code:'NOT_FOUND'});await AuditLog.create({actor:session.user.id,action:'movie.archive',entity:'Movie',entityId:id,metadata:{title:movie.title}});return Response.json({ok:true});}catch(error){return apiError(error);}}
