import { useState, type FormEvent } from 'react';
import { formatLkr } from '../../shared/contracts';
import { api } from '../api';
import type { Bootstrap } from '../components';
import { Empty } from '../components';
import { useCart } from '../store';

export function Checkout({ bootstrap }: { bootstrap: Bootstrap }) {
  const [cart, setCart] = useCart(); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [result, setResult] = useState<any>(); const [idempotencyKey] = useState(() => crypto.randomUUID().replaceAll('-', ''));
  if (!cart.length && !result) return <Empty title="Your bag is empty">Add a piece before checking out.</Empty>;
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setBusy(true); setError(''); const data = new FormData(event.currentTarget); const payload = { items: cart.map(i => ({ variantId: i.variantId, quantity: i.quantity })), address: { name: data.get('name'), mobile: data.get('mobile'), email: data.get('email'), line1: data.get('line1'), line2: data.get('line2') || undefined, district: data.get('district'), city: data.get('city'), postalCode: data.get('postalCode') || undefined, instructions: data.get('instructions') || undefined }, paymentMethod: data.get('paymentMethod'), channel: data.get('channel') || 'web' };
    try { const response = await api<any>('/checkout', { method: 'POST', headers: { 'idempotency-key': idempotencyKey }, body: JSON.stringify(payload) }); setResult(response); setCart([]); if (response.trackingToken) localStorage.setItem(`tracking:${response.order.orderNumber}`, response.trackingToken); } catch (e: any) { setError(e.message); } finally { setBusy(false); } };
  if (result) { const summary = `Order ${result.order.orderNumber}\n${result.order.items.map((i:any) => `${i.productName} (${Object.values(i.options).join('/')}) × ${i.quantity}`).join('\n')}\nTotal: ${formatLkr(result.order.total)}\nPayment: ${result.order.paymentMethod}`; return <section className="confirmation"><p className="eyebrow">Order saved</p><h1>Thank you for your order.</h1><p>Your reference is <strong>{result.order.orderNumber}</strong>. Stock is reserved while the order awaits confirmation.</p><div className="confirmation-box"><strong>Total</strong><span>{formatLkr(result.order.total)}</span><p>{result.order.paymentMethod === 'bank_transfer' ? 'Payment remains pending until an authorized staff member verifies the transfer. Contact the store for approved bank instructions.' : 'Cash on delivery was selected. This is not recorded as money received until collection.'}</p></div><a className="button" href={`/track?order=${result.order.orderNumber}&token=${result.trackingToken || ''}`}>Track this order</a>{bootstrap.store.whatsapp && <a className="button whatsapp-order" target="_blank" rel="noreferrer" href={`https://wa.me/${bootstrap.store.whatsapp}?text=${encodeURIComponent(summary)}`}>Continue in WhatsApp</a>}<p className="muted">WhatsApp will open with a prepared summary. You must press Send; opening the app does not send or confirm receipt.</p><button className="text-button" onClick={() => navigator.clipboard.writeText(summary)}>Copy order summary</button></section>; }
  return <><div className="checkout-steps checkout-progress"><div><b>1</b><span>Cart</span></div><i/><div className="active"><b>2</b><span>Details</span></div><i/><div><b>3</b><span>Payment</span></div></div><section className="checkout"><form onSubmit={submit}><p className="eyebrow">Secure guest checkout</p><h1>Delivery details</h1><div className="form-grid"><label>Full name<input name="name" required minLength={2}/></label><label>Mobile number<input name="mobile" required inputMode="tel" pattern="\+?[0-9]{9,15}"/></label><label>Email (optional)<input name="email" type="email"/></label><label className="span-2">Address<input name="line1" required minLength={5}/></label><label className="span-2">Address line 2 (optional)<input name="line2"/></label><label>District<input name="district" required/></label><label>City<input name="city" required/></label><label>Postal code (optional)<input name="postalCode"/></label><label className="span-2">Delivery instructions (optional)<textarea name="instructions" maxLength={500}/></label></div><fieldset><legend>Payment method</legend><label className="radio"><input name="paymentMethod" type="radio" value="cod" required/> Cash on delivery</label><label className="radio"><input name="paymentMethod" type="radio" value="bank_transfer" required/> Manual bank transfer (verification required)</label></fieldset>{error && <div className="form-error" role="alert">{error} Review your bag and try again.</div>}<button className="button full" disabled={busy}>{busy ? 'Securing your order…' : 'Place order'}</button><p className="muted">Your order is only successful after the server confirms it here. Prices and stock are checked again when you submit.</p></form><aside><h2>Order summary</h2>{cart.map(i => <div className="summary-line" key={i.variantId}><span>{i.productName} × {i.quantity}<small>{Object.values(i.options).join(' / ')}</small></span><strong>{formatLkr(i.price * i.quantity)}</strong></div>)}<div className="summary-total"><span>Current item total</span><strong>{formatLkr(cart.reduce((s,i) => s + i.price * i.quantity, 0))}</strong></div><p>Delivery is calculated from configured service zones. No unapproved fee or promise is assumed.</p></aside></section></>;
}

export function Track() { const query = typeof location === 'undefined' ? new URLSearchParams() : new URLSearchParams(location.search); const [order, setOrder] = useState<any>(); const [error, setError] = useState(''); const submit = async (e: FormEvent<HTMLFormElement>) => { e.preventDefault(); const d = new FormData(e.currentTarget); try { setOrder(await api('/track', { method: 'POST', body: JSON.stringify({ orderNumber: d.get('orderNumber'), trackingToken: d.get('trackingToken') }) })); setError(''); } catch (e:any) { setError(e.message); } }; return <section className="section narrow"><p className="eyebrow">Private order status</p><h1>Track your order</h1><p>Use both the order reference and the private tracking credential from your confirmation. A telephone number alone cannot access an order.</p><form className="track-form" onSubmit={submit}><label>Order reference<input name="orderNumber" defaultValue={query.get('order') || ''} required/></label><label>Tracking credential<input name="trackingToken" defaultValue={query.get('token') || ''} required/></label><button className="button">Show status</button></form>{error && <div className="form-error">{error}</div>}{order && <div className="tracked"><h2>{order.orderNumber}</h2><p><strong>Order:</strong> {order.lifecycle.replaceAll('_',' ')}</p><p><strong>Payment:</strong> {order.paymentState.replaceAll('_',' ')}</p><p><strong>Fulfilment:</strong> {order.fulfilmentState.replaceAll('_',' ')}</p><strong>{formatLkr(order.total)}</strong></div>}</section>; }
