import { ArrowRight, Heart, MessageCircle, Minus, PackageCheck, Plus, ShieldCheck, SlidersHorizontal, Trash2, Truck, X } from 'lucide-react';
import { useEffect, useMemo, useState, type SyntheticEvent } from 'react';
import type { PublicProduct } from '../../shared/contracts';
import { formatLkr } from '../../shared/contracts';
import { api } from '../api';
import type { Bootstrap } from '../components';
import { Empty } from '../components';
import { addCart, toggleWish, useCart } from '../store';

type ListResult = { items: PublicProduct[]; page: number; pages: number; total: number };
const fallbackImage = 'data:image/svg+xml,%3Csvg xmlns="http://www.w3.org/2000/svg" width="800" height="1000"%3E%3Crect width="100%25" height="100%25" fill="%23e8e0d1"/%3E%3Ctext x="50%25" y="50%25" text-anchor="middle" fill="%2364748b" font-family="sans-serif" font-size="28"%3EImage coming soon%3C/text%3E%3C/svg%3E';
const recoverImage = (event: SyntheticEvent<HTMLImageElement>) => {
  event.currentTarget.onerror = null;
  event.currentTarget.src = fallbackImage;
};

function ProductCard({ product }: { product: PublicProduct }) {
  const prices = product.variants.map(v => v.salePrice ?? v.price); const min = Math.min(...prices); const varied = new Set(prices).size > 1;
  const available = product.variants.some(v => v.available > 0);
  const colours=Array.from(new Set(product.variants.map(v=>v.options.Colour).filter((colour): colour is string => Boolean(colour)))).slice(0,4);
  const swatch=(colour:string)=>({forest:'#17483e',sand:'#c7b69b',navy:'#172a46',blue:'#6f8fae',black:'#1d2326',cream:'#e8dfcf',olive:'#667153',rose:'#b87a78'}[colour.toLowerCase()]||'#a8b0b2');
  return <article className="product-card"><div className="card-image"><a href={`/products/${product.slug}`}><img src={product.images[0]?.url || fallbackImage} alt={product.images[0]?.alt || product.name} loading="lazy" onError={recoverImage}/></a><button aria-label={`Save ${product.name}`} onClick={() => toggleWish(product.slug)}><Heart /></button>{!available&&<span className="card-badge">Sold out</span>}</div><a className="card-copy" href={`/products/${product.slug}`}><small>{product.category?.name || 'Clothing'}</small><h3>{product.name}</h3><p>{varied && 'From '}{formatLkr(min)}</p>{colours.length>0&&<div className="card-swatches" aria-label={`${colours.length} colours`}>{colours.map(c=><i key={c} title={c} style={{background:swatch(c)}}/>)}</div>}</a></article>;
}

export function Home({ bootstrap, initial }: { bootstrap: Bootstrap; initial?: any }) {
  const [products, setProducts] = useState<PublicProduct[]>(initial?.products || []);
  useEffect(() => { if (!initial?.products) api<ListResult>('/products?limit=8').then(r => setProducts(r.items)).catch(() => {}); }, []);
  const hero=bootstrap.homepage?.heroImage||'/assets/fashion-hero-v1.png';
  return <><section className="hero" style={{backgroundImage:`url(${hero})`}}><div><p className="eyebrow">New season · everyday icons</p><h1>{bootstrap.homepage?.heroTitle || 'Wear Your Story'}</h1><p>{bootstrap.homepage?.heroText || 'High-quality clothing for every moment, thoughtfully selected for life in motion.'}</p><div className="hero-actions"><a className="button" href="/shop">Shop now <ArrowRight/></a><a className="button secondary" href="/shop">Explore collection</a></div></div></section>
    <section className="home-benefits"><div><ShieldCheck/><span><strong>Quality clothing</strong><small>Made to last</small></span></div><div><Truck/><span><strong>Islandwide delivery</strong><small>Configured Sri Lanka zones</small></span></div><div><PackageCheck/><span><strong>Secure ordering</strong><small>Server-validated checkout</small></span></div><div><MessageCircle/><span><strong>Order on WhatsApp</strong><small>Quick and convenient</small></span></div></section>
    {bootstrap.categories.length > 0 && <section className="section home-section"><div className="section-heading"><h2>Shop by category</h2><a href="/shop">View all <ArrowRight/></a></div><div className="category-grid">{bootstrap.categories.slice(0, 7).map(c => <a href={`/shop?category=${c.slug}`} key={c.slug}><div><img src={c.image?.url || fallbackImage} alt={c.image?.alt || c.name} onError={recoverImage}/></div><span>{c.name}</span></a>)}</div></section>}
    {products.length > 0 && <section className="section home-section arrivals"><div className="section-heading"><h2>New arrivals</h2><a href="/shop">View all <ArrowRight/></a></div><div className="product-grid">{products.map(p => <ProductCard key={p.id} product={p}/>)}</div></section>}
    <section className="campaign-grid"><a href="/shop?category=men" className="campaign men"><div><p>New essentials</p><h2>Men’s<br/>Collection</h2><span>Style for every journey</span><b>Shop men <ArrowRight/></b></div></a><a href="/shop?category=women" className="campaign women"><div><p>Season edit</p><h2>Women’s<br/>Collection</h2><span>Confidence looks good on you</span><b>Shop women <ArrowRight/></b></div></a></section></>;
}

export function Shop({ initial, bootstrap, search }: { initial?: any; bootstrap: Bootstrap; search: string }) {
  const [result, setResult] = useState<ListResult>(initial?.list || { items:[], page:1, pages:0, total:0 });
  const [loading, setLoading] = useState(!initial?.list);
  const [error, setError] = useState('');
  const params = new URLSearchParams(search);
  const load = () => { setLoading(true); setError(''); api<ListResult>(`/products?${params}`).then(setResult).catch(caught => setError(caught.message)).finally(() => setLoading(false)); };
  useEffect(() => { if (!initial?.list) load(); }, [search]);
  const update = (key:string,value:string) => { if(value)params.set(key,value);else params.delete(key);params.delete('page');const query=params.toString();location.href=`/shop${query?`?${query}`:''}`; };
  const without = (key:string) => { const next=new URLSearchParams(params);next.delete(key);next.delete('page');const query=next.toString();return `/shop${query?`?${query}`:''}`; };
  const categorySlug=params.get('category')||'';
  const query=params.get('q')?.trim()||'';
  const selectedCategory=bootstrap.categories.find(category=>category.slug===categorySlug);
  const categoryName=selectedCategory?.name||(categorySlug?categorySlug.split('-').map(word=>word.charAt(0).toUpperCase()+word.slice(1)).join(' '):'');
  const onSale=params.get('sale')==='true';
  const title=categoryName?(onSale?`${categoryName} sale`:categoryName):query?'Search results':onSale?'Sale':'Shop all';
  const activeFilters:Array<{key:string;label:string}>=[];
  if(categorySlug)activeFilters.push({key:'category',label:categoryName});
  if(query)activeFilters.push({key:'q',label:`Search: ${query}`});
  if(params.get('size'))activeFilters.push({key:'size',label:`Size: ${params.get('size')}`});
  if(params.get('colour'))activeFilters.push({key:'colour',label:`Colour: ${params.get('colour')}`});
  if(params.get('available')==='true')activeFilters.push({key:'available',label:'In stock'});
  if(onSale)activeFilters.push({key:'sale',label:'Sale'});
  if(params.get('sort')&&params.get('sort')!=='newest')activeFilters.push({key:'sort',label:`Sort: ${params.get('sort')?.replaceAll('-',' ')}`});
  const refinementCount=activeFilters.filter(filter=>filter.key!=='category').length;
  const revealFilters=Boolean(query||params.get('size')||params.get('colour')||params.get('available')||params.get('sort')&&params.get('sort')!=='newest');
  const sortLabel=params.get('sort')==='price-asc'?'Price: low to high':params.get('sort')==='price-desc'?'Price: high to low':'Newest first';
  return <section className="section shop">
    <header className="shop-compact-head"><div><nav className="shop-breadcrumbs" aria-label="Breadcrumb"><a href="/">Home</a><span aria-hidden="true">/</span><a href="/shop">Shop</a>{title!=='Shop all'&&<><span aria-hidden="true">/</span><span aria-current="page">{title}</span></>}</nav><h1>{title}</h1></div><div className="shop-count" aria-live="polite"><strong>{loading?'—':result.total}</strong><span>{loading?'Updating':result.total===1?'piece':'pieces'}</span></div></header>
    <nav className="shop-category-tabs" aria-label="Shop categories"><a className={!categorySlug&&!onSale?'active':''} aria-current={!categorySlug&&!onSale?'page':undefined} href="/shop">All products</a>{bootstrap.categories.map(category=><a className={category.slug===categorySlug?'active':''} aria-current={category.slug===categorySlug?'page':undefined} href={`/shop?category=${category.slug}`} key={category.slug}>{category.name}</a>)}<a className={`sale-tab ${onSale?'active':''}`} aria-current={onSale&&!categorySlug?'page':undefined} href="/shop?sale=true">Sale</a></nav>
    <details className="shop-filter-panel" open={revealFilters||undefined}><summary><span><SlidersHorizontal/><strong>Filters &amp; sort</strong><small>{refinementCount?`${refinementCount} active`:'Optional'}</small></span><b>{sortLabel}</b></summary><div className="shop-filter-body">{activeFilters.length>0&&<div className="active-filters" aria-label="Active filters">{activeFilters.map(filter=><a href={without(filter.key)} key={filter.key}>{filter.label}<X aria-hidden="true"/></a>)}<a className="clear-filters" href="/shop">Clear all</a></div>}<div className="filters"><input aria-label="Search products" placeholder="Search name, description or tag" defaultValue={query} onKeyDown={event=>event.key==='Enter'&&update('q',event.currentTarget.value)}/><select aria-label="Size" value={params.get('size')||''} onChange={event=>update('size',event.target.value)}><option value="">All sizes</option>{['XS','S','M','L','XL','2XL','3XL','One Size'].map(size=><option key={size}>{size}</option>)}</select><select aria-label="Availability" value={params.get('available')||''} onChange={event=>update('available',event.target.value)}><option value="">Any availability</option><option value="true">In stock</option></select><select aria-label="Sort products" value={params.get('sort')||'newest'} onChange={event=>update('sort',event.target.value)}><option value="newest">Newest</option><option value="price-asc">Price: low to high</option><option value="price-desc">Price: high to low</option></select></div></div></details>
    {loading?<div className="shop-loading"><span/><p>Updating the collection…</p></div>:error?<Empty title="We couldn't load the collection"><button className="button" onClick={load}>Try again</button></Empty>:result.items.length?<><div className="product-grid">{result.items.map(product=><ProductCard key={product.id} product={product}/>)}</div><div className="pagination">{Array.from({length:result.pages},(_,index)=><a className={index+1===result.page?'active':''} key={index} href={`?${new URLSearchParams({...Object.fromEntries(params),page:String(index+1)})}`}>{index+1}</a>)}</div></>:<div className="shop-empty"><span>No matches</span><h2>No pieces found</h2><p>Try a different size or search term, or return to the complete collection.</p><a className="button secondary" href="/shop">View all products</a></div>}
  </section>;
}

export function ProductDetail({ product: seeded, bootstrap }: { product?: PublicProduct; bootstrap: Bootstrap }) {
  const slug = typeof location === 'undefined' ? '' : location.pathname.split('/').pop()!; const [product, setProduct] = useState<PublicProduct | undefined>(seeded); const [error, setError] = useState('');
  const [options, setOptions] = useState<Record<string, string>>({}); const [qty, setQty] = useState(1); const [added, setAdded] = useState(false);
  useEffect(() => { if (!product) api<PublicProduct>(`/products/${slug}`).then(setProduct).catch(e => setError(e.message)); }, [slug]);
  const optionNames = useMemo(() => Array.from(new Set(product?.variants.flatMap(v => Object.keys(v.options)) || [])), [product]);
  const selected = product?.variants.find(v => optionNames.every(k => options[k] === v.options[k]));
  if (error) return <Empty title="This piece is unavailable">{error}</Empty>; if (!product) return <div className="loading">Loading product…</div>;
  const choose = (name: string, value: string) => setOptions(o => ({ ...o, [name]: value }));
  const add = () => { if (!selected || selected.available < qty) return; addCart({ variantId: selected.id, productName: product.name, slug: product.slug, sku: selected.sku, options: selected.options, price: selected.salePrice ?? selected.price, quantity: qty, image: product.images[0]?.url }); setAdded(true); };
  const message = selected ? `${product.name} — ${Object.values(selected.options).join(' / ')} — quantity ${qty}` : product.name;
  const gallery=(selected as any)?.images?.length?(selected as any).images:product.images.length?product.images:[{url:fallbackImage,alt:'Image coming soon'}];
  return <><div className="breadcrumbs"><a href="/">Home</a><span>›</span><a href="/shop">Shop</a><span>›</span><span>{product.name}</span></div><section className="product-detail"><div className="thumbs">{gallery.map((i:any,index:number)=><button key={i.url+index}><img src={i.url} alt=""/></button>)}</div><div className="gallery">{gallery.map((i:any,index:number)=><img key={`${i.url}-${index}`} src={i.url} alt={i.alt||product.name}/>)}</div><div className="product-panel"><span className="new-pill">New arrival</span><h1>{product.name}</h1><div className="price">{selected?formatLkr(selected.salePrice??selected.price):`From ${formatLkr(Math.min(...product.variants.map(v=>v.salePrice??v.price)))}`}</div><p>{product.description}</p>{optionNames.map(name=><fieldset key={name}><legend>{name}: <span>{options[name]||`Choose ${name.toLowerCase()}`}</span>{name.toLowerCase()==='size'&&<a href="/size-guide">Size guide</a>}</legend><div className={`chips ${name.toLowerCase()==='colour'?'colour-chips':''}`}>{Array.from(new Set(product.variants.map(v=>v.options[name]).filter(Boolean))).map(value=>{const possible=product.variants.some(v=>v.options[name]===value&&v.available>0&&Object.entries(options).filter(([k])=>k!==name).every(([k,val])=>v.options[k]===val));return <button className={options[name]===value?'selected':''} disabled={!possible} onClick={()=>choose(name,value!)} key={value}>{value}</button>})}</div></fieldset>)}
    <div className="quantity-row"><span>Quantity:</span><div className="quantity"><button onClick={()=>setQty(Math.max(1,qty-1))} aria-label="Decrease quantity"><Minus/></button><span>{qty}</span><button onClick={()=>setQty(qty+1)} aria-label="Increase quantity"><Plus/></button></div>{selected&&<p className={`availability ${selected.status}`}>✓ {selected.status.replaceAll('_',' ')}{selected.available<qty&&' — reduce quantity'}</p>}</div><button className="button secondary full" disabled={!selected||selected.available<qty} onClick={add}>{added?'Added to cart':selected?'Add to cart':`Choose ${optionNames.join(' and ')}`}</button><button className="button full" disabled={!selected||selected.available<qty} onClick={()=>{add();location.href='/checkout'}}>Buy now</button>{bootstrap.store.whatsapp&&<a className={`button whatsapp-order full ${!selected?'disabled':''}`} aria-disabled={!selected} href={selected?`https://wa.me/${bootstrap.store.whatsapp}?text=${encodeURIComponent(`Hello, I would like to ask about ${message}. I understand I still need to press Send in WhatsApp.`)}`:undefined}><MessageCircle/> Order on WhatsApp</a>}<details><summary>Product information</summary><p>{product.material&&`Material: ${product.material}. `}{product.fit&&`Fit: ${product.fit}. `}{product.care}</p></details><details><summary>Delivery & returns</summary><p>Delivery cost and approved estimates appear at checkout.</p></details></div><div className="product-trust"><span><ShieldCheck/><b>Quality checked</b></span><span><PackageCheck/><b>Easy order tracking</b></span><span><Truck/><b>Islandwide options</b></span></div></section></>;
}

export function Cart(){const[cart,setCart]=useCart();const total=cart.reduce((s,i)=>s+i.price*i.quantity,0);if(!cart.length)return <Empty title="Your cart is empty">Explore the collection and choose a size and colour to get started. <a href="/shop">Shop now</a></Empty>;const update=(id:string,n:number)=>setCart(cart.map(i=>i.variantId===id?{...i,quantity:Math.max(1,Math.min(20,n))}:i));return <section className="cart-page"><div className="checkout-steps"><div className="active"><b>1</b><span>Cart</span></div><i/><div><b>2</b><span>Details</span></div><i/><div><b>3</b><span>Payment</span></div></div><h1>Your cart</h1><div className="cart-layout"><div className="cart-lines">{cart.map(line=><article key={line.variantId}><img src={line.image||fallbackImage} alt=""/><div className="cart-copy"><a href={`/products/${line.slug}`}><strong>{line.productName}</strong></a><p>{Object.values(line.options).join(' / ')}</p><div className="mini-qty"><button onClick={()=>update(line.variantId,line.quantity-1)}><Minus/></button><span>{line.quantity}</span><button onClick={()=>update(line.variantId,line.quantity+1)}><Plus/></button></div></div><strong className="line-price">{formatLkr(line.price*line.quantity)}</strong><button className="trash" aria-label={`Remove ${line.productName}`} onClick={()=>setCart(cart.filter(i=>i.variantId!==line.variantId))}><Trash2/></button></article>)}</div><aside className="cart-total"><h2>Order summary</h2><div><span>Subtotal</span><strong>{formatLkr(total)}</strong></div><div><span>Delivery</span><span>Calculated at checkout</span></div><hr/><div className="grand-total"><span>Total</span><strong>{formatLkr(total)}</strong></div><p>Prices and availability are securely rechecked before your order is saved.</p><a className="button full" href="/checkout">Proceed to checkout <ArrowRight/></a><a className="button secondary full" href="/shop">Continue shopping</a></aside></div></section>}

export function Wishlist() { const [items, setItems] = useState<PublicProduct[]>([]); useEffect(() => { const slugs: string[] = JSON.parse(localStorage.getItem('clothing-store-wishlist-v1') || '[]'); Promise.all(slugs.map(s => api<PublicProduct>(`/products/${s}`).catch(() => null))).then(p => setItems(p.filter(Boolean) as PublicProduct[])); }, []); return <section className="section"><h1>Saved pieces</h1>{items.length ? <div className="product-grid">{items.map(p => <ProductCard product={p} key={p.id}/>)}</div> : <Empty title="Nothing saved yet">Use the heart on a product to keep it here. Availability and pricing refresh from the store.</Empty>}</section>; }
