'use client';

import { Ban, CheckCircle2, CloudUpload, Link2, LoaderCircle, Pause, Play, RefreshCw, Save, Trash2 } from 'lucide-react';
import { useRef, useState, type FormEvent } from 'react';
import { useRouter } from 'next/navigation';
import { uploadApiFetch as fetch } from '@/lib/client/upload-json';

type MirrorRow = { _id: string; providerName: string; providerType: string; active: boolean; supportsResume: boolean; requiresLogin: boolean; healthStatus: string; lastCheckedAt?: string };
export type VersionRow = { _id: string; quality: string; resolution: string; releaseType: string; videoCodec: string; audioCodec?: string; container: string; fileName: string; fileSize: number; active: boolean; rightsStatus: string; deletionStatus: string; mirrors: MirrorRow[] };
type UploadedAsset = { id: string; objectKey: string; size: number };

const csrf = () => decodeURIComponent(document.cookie.split('; ').find((item) => item.startsWith('cinerusubs_csrf='))?.split('=').slice(1).join('=') || '');
const mime = (file: File) => file.type || ({ mkv: 'video/x-matroska', webm: 'video/webm' }[file.name.split('.').pop()?.toLocaleLowerCase() || ''] || 'video/mp4');
const size = (bytes: number) => bytes >= 1_000_000_000 ? `${(bytes / 1_000_000_000).toFixed(2)} GB` : `${(bytes / 1_000_000).toFixed(1)} MB`;
const delay = (milliseconds: number) => new Promise((resolve) => window.setTimeout(resolve, milliseconds));

function put(url: string, body: Blob, signal: AbortSignal, onProgress: (loaded: number) => void, headers: Record<string, string> = {}) {
  return new Promise<string>((resolve, reject) => { const request = new XMLHttpRequest(); request.open('PUT', url); for (const [key, value] of Object.entries(headers)) request.setRequestHeader(key, value); request.upload.onprogress = (event) => onProgress(event.loaded); request.onerror = () => reject(new Error('R2 rejected the upload. Check bucket CORS and network access.')); request.onload = () => request.status >= 200 && request.status < 300 ? resolve(request.getResponseHeader('ETag') || '') : reject(new Error(`R2 rejected the upload (${request.status}).`)); const abort = () => { request.abort(); reject(new DOMException('Upload cancelled.', 'AbortError')); }; signal.addEventListener('abort', abort, { once: true }); request.onloadend = () => signal.removeEventListener('abort', abort); request.send(body); });
}

export function MediaVersionManager({ contentId, initialVersions }: { contentId: string; initialVersions: VersionRow[] }) {
  const router = useRouter(); const fileInput = useRef<HTMLInputElement>(null); const abortRef = useRef<AbortController | null>(null); const pausedRef = useRef(false);
  const [pending, setPending] = useState(false); const [paused, setPaused] = useState(false); const [percent, setPercent] = useState(0); const [progress, setProgress] = useState(''); const [error, setError] = useState('');

  async function uploadAsset(file: File): Promise<UploadedAsset> {
    const controller = new AbortController(); abortRef.current = controller; const headers = { 'Content-Type': 'application/json', 'x-csrf-token': csrf() }; const startedAt = performance.now(); let multipart: { assetId: string; uploadId: string } | null = null;
    const report = (loaded: number, total = file.size, part?: string) => { const seconds = Math.max((performance.now() - startedAt) / 1_000, .1); const speed = loaded / seconds; const eta = speed > 0 ? Math.max(0, (total - loaded) / speed) : 0; setPercent(Math.min(100, Math.round(loaded / total * 100))); setProgress(`${part ? `${part} · ` : ''}${size(loaded)} of ${size(total)} · ${(speed / 1_000_000).toFixed(1)} MB/s · ${Math.ceil(eta / 60)} min remaining`); };
    try {
      const body = { kind: 'media', fileName: file.name, contentType: mime(file), size: file.size, linkedModel: 'Movie', linkedId: contentId };
      if (file.size > 500_000_000) {
        const start = await fetch('/api/admin/uploads/multipart/start', { method: 'POST', headers, body: JSON.stringify(body), signal: controller.signal }); const ticket = await start.json(); if (!start.ok) throw new Error(ticket.error?.message || 'Multipart upload could not start.'); multipart = ticket;
        const parts: { ETag: string; PartNumber: number }[] = []; let uploaded = 0; const partCount = Math.ceil(file.size / ticket.partSize);
        for (let index = 0; index < partCount; index++) {
          while (pausedRef.current) { setProgress(`Paused before part ${index + 1} of ${partCount}`); await delay(250); if (controller.signal.aborted) throw new DOMException('Upload cancelled.', 'AbortError'); }
          const partNumber = index + 1; const chunk = file.slice(index * ticket.partSize, Math.min(file.size, (index + 1) * ticket.partSize)); let uploadedPart = false; let lastError: unknown;
          for (let attempt = 1; attempt <= 3 && !uploadedPart; attempt++) {
            try { setProgress(`Signing part ${partNumber} of ${partCount}${attempt > 1 ? ` · retry ${attempt - 1}` : ''}`); const signature = await fetch(`/api/admin/uploads/multipart/${ticket.assetId}/part`, { method: 'POST', headers, body: JSON.stringify({ uploadId: ticket.uploadId, partNumber }), signal: controller.signal }); const signed = await signature.json(); if (!signature.ok) throw new Error(signed.error?.message || `Part ${partNumber} could not be signed.`); const etag = await put(signed.uploadUrl, chunk, controller.signal, (loaded) => report(uploaded + loaded, file.size, `Part ${partNumber}/${partCount}`)); if (!etag) throw new Error('R2 did not expose ETag. Add it to CORS exposeHeaders.'); parts.push({ ETag: etag, PartNumber: partNumber }); uploaded += chunk.size; report(uploaded, file.size, `Part ${partNumber}/${partCount}`); uploadedPart = true; }
            catch (cause) { lastError = cause; if (cause instanceof DOMException && cause.name === 'AbortError') throw cause; if (attempt < 3) await delay(600 * attempt); }
          }
          if (!uploadedPart) throw lastError;
        }
        setProgress('Finalizing multipart upload…'); const complete = await fetch(`/api/admin/uploads/multipart/${ticket.assetId}/complete`, { method: 'POST', headers, body: JSON.stringify({ uploadId: ticket.uploadId, parts }), signal: controller.signal }); const result = await complete.json(); if (!complete.ok) throw new Error(result.error?.message || 'Multipart upload could not be finalized.'); return result.asset;
      }
      const signedResponse = await fetch('/api/admin/uploads/presign', { method: 'POST', headers, body: JSON.stringify(body), signal: controller.signal }); const ticket = await signedResponse.json(); if (!signedResponse.ok) throw new Error(ticket.error?.message || 'Upload could not be signed.'); await put(ticket.uploadUrl, file, controller.signal, (loaded) => report(loaded), ticket.headers); const complete = await fetch(`/api/admin/uploads/${ticket.assetId}/complete`, { method: 'POST', headers: { 'x-csrf-token': csrf() }, signal: controller.signal }); const result = await complete.json(); if (!complete.ok) throw new Error(result.error?.message || 'Uploaded object could not be verified.'); return result.asset;
    } catch (cause) { if (multipart) await fetch(`/api/admin/uploads/multipart/${multipart.assetId}`, { method: 'DELETE', headers: { 'Content-Type': 'application/json', 'x-csrf-token': csrf() }, body: JSON.stringify({ uploadId: multipart.uploadId }) }).catch(() => undefined); throw cause; }
  }

  async function createVersion(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const file = fileInput.current?.files?.[0]; if (!file) { setError('Choose an MP4, MKV, or WEBM movie file.'); return; }
    setPending(true); setError(''); setPercent(0); setProgress('Requesting secure upload…'); pausedRef.current = false; setPaused(false);
    try { const form = new FormData(event.currentTarget); const value = (key: string) => String(form.get(key) || '').trim(); const list = (key: string) => value(key).split(',').map((item) => item.trim()).filter(Boolean); const asset = await uploadAsset(file); setProgress('Creating media version…'); const response = await fetch('/api/admin/media-versions', { method: 'POST', headers: { 'Content-Type': 'application/json', 'x-csrf-token': csrf() }, body: JSON.stringify({ assetId: asset.id, contentId, contentType: 'movie', quality: value('quality'), resolution: value('resolution'), releaseType: value('releaseType'), videoCodec: value('videoCodec'), audioCodec: value('audioCodec') || undefined, container: value('container'), audioLanguages: list('audioLanguages'), embeddedSubtitleLanguages: list('embeddedSubtitleLanguages'), rightsStatus: value('rightsStatus'), regionRestrictions: [], active: form.has('active') }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error?.message || 'Media version could not be created.'); setPercent(100); setProgress('Upload complete and media version ready.'); if (fileInput.current) fileInput.current.value = ''; router.refresh(); }
    catch (cause) { setError(cause instanceof DOMException && cause.name === 'AbortError' ? 'Upload cancelled.' : cause instanceof Error ? cause.message : 'Upload failed.'); setProgress(''); setPercent(0); }
    finally { abortRef.current = null; setPending(false); }
  }

  async function versionAction(id: string, action: 'toggle' | 'delete', active = false) { setError(''); const response = await fetch(`/api/admin/media-versions/${id}`, { method: action === 'delete' ? 'DELETE' : 'PATCH', headers: { 'Content-Type': 'application/json', 'x-csrf-token': csrf() }, body: action === 'toggle' ? JSON.stringify({ active: !active }) : undefined }); const result = await response.json(); if (!response.ok) setError(result.error?.message || 'Media version update failed.'); else router.refresh(); }
  async function addMirror(event: FormEvent<HTMLFormElement>, versionId: string) { event.preventDefault(); const form = new FormData(event.currentTarget); const response = await fetch(`/api/admin/media-versions/${versionId}/mirrors`, { method: 'POST', headers: { 'Content-Type': 'application/json', 'x-csrf-token': csrf() }, body: JSON.stringify({ providerName: String(form.get('providerName') || ''), providerType: String(form.get('providerType') || 'external'), url: String(form.get('url') || ''), priority: Number(form.get('priority') || 100), supportsResume: form.has('supportsResume'), requiresLogin: form.has('requiresLogin'), active: true }) }); const result = await response.json(); if (!response.ok) setError(result.error?.message || 'Mirror could not be added.'); else { event.currentTarget.reset(); router.refresh(); } }
  async function mirrorAction(id: string, action: 'check' | 'disable') { const response = await fetch(action === 'check' ? `/api/admin/mirrors/${id}/check` : `/api/admin/mirrors/${id}`, { method: action === 'check' ? 'POST' : 'DELETE', headers: { 'x-csrf-token': csrf() } }); const result = await response.json(); if (!response.ok) setError(result.error?.message || 'Mirror update failed.'); else router.refresh(); }

  return <section className="media-version-manager"><header><CloudUpload/><div><span>Cloudflare R2</span><h2>Media versions</h2><p>Upload authorized movie files directly to the private media bucket, then attach optional mirrors.</p></div></header>
    <form className="media-version-form" onSubmit={createVersion}><div className="media-version-fields"><label>Quality<select name="quality" defaultValue="1080p"><option>480p</option><option>720p</option><option>1080p</option><option>1440p</option><option>2160p</option></select></label><label>Resolution<input name="resolution" required defaultValue="1920×1080"/></label><label>Release type<select name="releaseType" defaultValue="WEB-DL"><option>WEB-DL</option><option>WEBRip</option><option>BluRay</option><option>HDRip</option><option>DVDRip</option><option>Other</option></select></label><label>Video codec<select name="videoCodec" defaultValue="H264"><option>H264</option><option>H265</option><option>AV1</option></select></label><label>Container<select name="container" defaultValue="MP4"><option>MP4</option><option>MKV</option><option>WEBM</option></select></label><label>Audio codec<input name="audioCodec" placeholder="AAC 5.1"/></label><label>Audio languages<input name="audioLanguages" placeholder="Sinhala, English"/></label><label>Embedded subtitles<input name="embeddedSubtitleLanguages" placeholder="Sinhala, English"/></label><label>Rights<select name="rightsStatus" defaultValue="licensed"><option value="owned">Owned</option><option value="licensed">Licensed</option><option value="public_domain">Public domain</option><option value="subtitle_only">Subtitle only</option><option value="unavailable">Unavailable</option></select></label><label>Movie file<input ref={fileInput} name="file" type="file" accept=".mp4,.mkv,.webm,video/mp4,video/webm,video/x-matroska" required disabled={pending}/></label><label className="media-active-check"><input name="active" type="checkbox"/> Activate after upload</label></div><div className="media-upload-actions"><button className="admin-primary" disabled={pending}>{pending?<LoaderCircle className="spin"/>:<Save/>}Upload & add version</button>{pending&&<><button type="button" onClick={() => { pausedRef.current = !pausedRef.current; setPaused(pausedRef.current); }}>{paused?<Play/>:<Pause/>}{paused?'Resume':'Pause after part'}</button><button className="admin-danger" type="button" onClick={() => abortRef.current?.abort()}><Ban/>Cancel</button></>}</div>{progress&&<><div className="upload-meter"><i style={{width:`${percent}%`}}/></div><p className="upload-progress"><CheckCircle2/>{progress}</p></>}{error&&<p className="admin-form-error">{error}</p>}</form>
    <div className="media-version-records">{initialVersions.length ? initialVersions.map((version) => <article key={version._id}><header><div><b>{version.quality}</b><span>{version.releaseType} · {version.videoCodec} · {size(version.fileSize)}</span><small>{version.fileName}</small></div><em className={version.active?'ready':'inactive'}>{version.deletionStatus==='pending_deletion'?'Pending deletion':version.active?'Ready':'Disabled'}</em></header><div className="media-version-actions"><button type="button" onClick={() => versionAction(version._id,'toggle',version.active)}>{version.active?<Ban/>:<CheckCircle2/>}{version.active?'Disable':'Activate'}</button><button className="admin-danger" type="button" onClick={() => versionAction(version._id,'delete')}><Trash2/>Mark for deletion</button></div><div className="mirror-records">{version.mirrors.map((mirror) => <div key={mirror._id}><Link2/><span><b>{mirror.providerName}</b><small>{mirror.providerType} · {mirror.healthStatus}</small></span><button type="button" onClick={() => mirrorAction(mirror._id,'check')}><RefreshCw/>Check</button>{mirror.active&&<button type="button" onClick={() => mirrorAction(mirror._id,'disable')}><Ban/>Disable</button>}</div>)}</div><form className="mirror-form" onSubmit={(event) => addMirror(event,version._id)}><input name="providerName" required placeholder="Provider name"/><select name="providerType"><option value="external">External</option><option value="telegram">Telegram</option><option value="cloud_drive">Cloud drive</option><option value="custom">Custom</option></select><input name="url" type="url" required placeholder="https://…"/><input name="priority" type="number" defaultValue="100" min="0"/><label><input name="supportsResume" type="checkbox"/> Resume</label><label><input name="requiresLogin" type="checkbox"/> Login required</label><button type="submit"><Link2/>Add mirror</button></form></article>) : <div className="admin-empty"><b>No media versions</b><p>Upload the first authorized movie file above.</p></div>}</div>
  </section>;
}
