'use client';

import { HardDrive, LoaderCircle, ScanSearch } from 'lucide-react';
import { useState } from 'react';

type Result = { scanned:number;capped:boolean;buckets?:string[];missing:{count:number;sample:string[]};orphaned:{count:number;sample:string[]} };
type AssetRow={_id?:string;fileName?:string;kind?:string;bucket?:string;size?:number;status?:string;createdAt?:string};
type StorageProps={rows:{_id:string;bytes:number;count:number}[];bucketRows:{_id:string;bytes:number;count:number}[];growth:{today:{bytes:number;count:number};week:{bytes:number;count:number};month:{bytes:number;count:number}};largest:AssetRow[];recent:AssetRow[];totalBytes:number;totalFiles:number};
const size=(bytes:number)=>bytes>=1_000_000_000?`${(bytes/1_000_000_000).toFixed(2)} GB`:`${(bytes/1_000_000).toFixed(1)} MB`;
export function StorageAudit({rows,bucketRows,growth,largest,recent,totalBytes,totalFiles}:StorageProps){const[pending,setPending]=useState(false);const[result,setResult]=useState<Result|null>(null);const[error,setError]=useState('');async function scan(){setPending(true);setError('');try{const response=await fetch('/api/admin/storage/audit');const data=await response.json();if(!response.ok)throw new Error(data.error?.message||'Storage scan failed.');setResult(data);}catch(cause){setError(cause instanceof Error?cause.message:'Storage scan failed.');}finally{setPending(false);}}return <section className="storage-audit"><header><HardDrive/><div><h2>Storage overview</h2><p>{totalFiles.toLocaleString()} tracked files · {size(totalBytes)}</p></div><button className="admin-primary" type="button" onClick={scan} disabled={pending}>{pending?<LoaderCircle className="spin"/>:<ScanSearch/>}{pending?'Scanning':'Check both R2 buckets'}</button></header><div className="storage-bucket-grid">{bucketRows.map(row=><div key={row._id}><span>{row._id}</span><b>{size(row.bytes)}</b><small>{row.count.toLocaleString()} managed files</small></div>)}</div><div className="storage-kind-grid">{rows.map(row=><div key={row._id}><span>{row._id}</span><b>{size(row.bytes)}</b><small>{row.count.toLocaleString()} files</small></div>)}</div><div className="storage-growth"><article><span>Today</span><b>{size(growth.today.bytes)}</b><small>{growth.today.count} files</small></article><article><span>This week</span><b>{size(growth.week.bytes)}</b><small>{growth.week.count} files</small></article><article><span>This month</span><b>{size(growth.month.bytes)}</b><small>{growth.month.count} files</small></article></div><div className="storage-lists"><section><h3>Largest files</h3>{largest.map(item=><div key={item._id}><span><b>{item.fileName||'Managed object'}</b><small>{item.kind} · {item.status}</small></span><em>{size(Number(item.size||0))}</em></div>)}</section><section><h3>Recently uploaded</h3>{recent.map(item=><div key={item._id}><span><b>{item.fileName||'Managed object'}</b><small>{item.kind} · {item.createdAt?new Date(item.createdAt).toLocaleDateString('en-LK'):'—'}</small></span><em>{size(Number(item.size||0))}</em></div>)}</section></div>{result&&<div className="storage-findings"><article><b>{result.missing.count}</b><span>Database records missing in R2</span>{result.missing.sample.slice(0,3).map(key=><code key={key}>{key}</code>)}</article><article><b>{result.orphaned.count}</b><span>Untracked R2 objects</span>{result.orphaned.sample.slice(0,3).map(key=><code key={key}>{key}</code>)}</article><p>Scanned {result.scanned.toLocaleString()} objects across {result.buckets?.join(' and ')||'both buckets'}{result.capped?' (scan limit reached)':''}. Nothing is deleted automatically.</p></div>}{error&&<p className="admin-form-error">{error}</p>}</section>}
