'use client';

import { CheckCircle2, LoaderCircle, Upload } from 'lucide-react';
import { useRef, useState, type FormEvent } from 'react';
import { uploadApiFetch as fetch } from '@/lib/client/upload-json';
const csrf=()=>decodeURIComponent(document.cookie.split('; ').find((item)=>item.startsWith('cinerusubs_csrf='))?.split('=').slice(1).join('=')||'');
const mimeFor=(file:File)=>file.type||({srt:'application/x-subrip',vtt:'text/vtt',ass:'application/x-ass',zip:'application/zip'}[file.name.split('.').pop()?.toLowerCase()||'']||'application/octet-stream');
export function SubtitleForm({translatorLocked}:{translatorLocked:boolean}){const fileInput=useRef<HTMLInputElement>(null);const[pending,setPending]=useState(false);const[message,setMessage]=useState('');const[done,setDone]=useState(false);async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget;const data=new FormData(form);const file=fileInput.current?.files?.[0];if(!file){setMessage('Choose a subtitle file.');return;}setPending(true);setMessage('Requesting secure upload…');try{const headers={'Content-Type':'application/json','x-csrf-token':csrf()};const signed=await fetch('/api/admin/uploads/presign',{method:'POST',headers,body:JSON.stringify({kind:'subtitle',fileName:file.name,contentType:mimeFor(file),size:file.size})});const ticket=await signed.json();if(!signed.ok)throw new Error(ticket.error?.message||'Upload could not be signed.');setMessage('Uploading subtitle to R2…');const sent=await fetch(ticket.uploadUrl,{method:'PUT',headers:ticket.headers,body:file});if(!sent.ok)throw new Error('R2 rejected the upload. Check the bucket CORS policy.');setMessage('Verifying file integrity…');const completed=await fetch(`/api/admin/uploads/${ticket.assetId}/complete`,{method:'POST',headers:{'x-csrf-token':csrf()}});const completeResult=await completed.json();if(!completed.ok)throw new Error(completeResult.error?.message||'The uploaded file could not be verified.');setMessage('Creating subtitle draft…');const value=(key:string)=>String(data.get(key)||'').trim();const created=await fetch('/api/admin/subtitles',{method:'POST',headers,body:JSON.stringify({assetId:ticket.assetId,contentType:value('contentType'),contentId:value('contentId'),translatorId:value('translatorId')||undefined,language:value('language'),languageCode:value('languageCode'),releaseMatches:value('releaseMatches').split(',').map(item=>item.trim()).filter(Boolean),fps:value('fps')?Number(value('fps')):undefined,format:value('format'),hearingImpaired:data.has('hearingImpaired'),version:Number(value('version')||1)})});const result=await created.json();if(!created.ok)throw new Error(result.error?.message||'Subtitle draft could not be created.');setDone(true);setMessage(`Draft ${result.id} is ready for review.`);form.reset();}catch(error){setMessage(error instanceof Error?error.message:'Subtitle upload failed.');}finally{setPending(false);}}
return <form className="admin-editor subtitle-editor" onSubmit={submit}><details open><summary><span>1</span>Subtitle file & release<Upload/></summary><div className="admin-form-grid"><label>Subtitle file<input ref={fileInput} type="file" accept=".srt,.vtt,.ass,.zip" required/></label><label>Format<select name="format" required><option value="srt">SRT</option><option value="vtt">WebVTT</option><option value="ass">ASS</option><option value="zip">ZIP archive</option></select></label><label>Content type<select name="contentType"><option value="movie">Movie</option><option value="episode">Episode</option></select></label><label>Movie or episode database ID<input name="contentId" required pattern="[a-fA-F0-9]{24}"/></label><label>Language<input name="language" defaultValue="Sinhala" required/></label><label>Language code<input name="languageCode" defaultValue="si" required/></label><label className="span-2">Matched releases<input name="releaseMatches" placeholder="1080p WEB-DL, BluRay" required/><small>Comma separated release names help viewers choose the correct timing.</small></label><label>Frame rate<input name="fps" type="number" step="0.001" min="1" max="240"/></label><label>Version<input name="version" type="number" min="1" max="100" defaultValue="1"/></label>{!translatorLocked&&<label className="span-2">Translator profile ID<input name="translatorId" required pattern="[a-fA-F0-9]{24}"/></label>}<label className="check-line"><input name="hearingImpaired" type="checkbox"/> Hearing-impaired captions</label></div></details>{message&&<p className={done?'admin-success':'upload-progress'}>{done?<CheckCircle2/>:pending?<LoaderCircle className="spin"/>:null}{message}</p>}<button className="admin-primary" disabled={pending} type="submit">{pending?<LoaderCircle className="spin"/>:<Upload/>}Upload as draft</button></form>;}
