'use client';

import { Check, Database, LoaderCircle } from 'lucide-react';
import { useState, type MouseEvent } from 'react';

type Preview = Record<string, string | number | string[] | undefined>;
const labels: Record<string, string> = { title:'Title',originalTitle:'Original title',overview:'Overview',year:'Year',releaseDate:'Release date',runtime:'Runtime',genres:'Genres',languages:'Languages',countries:'Countries',posterUrl:'Poster',backdropUrl:'Backdrop',trailerUrl:'Trailer',imdbId:'IMDb ID',tmdbId:'TMDb ID',tmdbRating:'TMDb rating',cast:'Cast',crew:'Crew',suggestedSlug:'Suggested slug' };

export function TmdbImporter() {
  const [id,setId]=useState('');const[preview,setPreview]=useState<Preview|null>(null);const[selected,setSelected]=useState<Set<string>>(new Set());const[pending,setPending]=useState(false);const[message,setMessage]=useState('');
  async function load(){setPending(true);setMessage('');setPreview(null);try{const response=await fetch(`/api/admin/tmdb/preview?id=${encodeURIComponent(id)}`);const result=await response.json();if(!response.ok)throw new Error(result.error?.message||'Preview could not be loaded.');setPreview(result.preview);setSelected(new Set(Object.entries(result.preview as Preview).filter(([,value])=>value!==undefined&&value!==''&&(!Array.isArray(value)||value.length)).map(([key])=>key)));}catch(error){setMessage(error instanceof Error?error.message:'Preview could not be loaded.');}finally{setPending(false);}}
  function apply(event:MouseEvent<HTMLButtonElement>){const form=event.currentTarget.closest('form');if(!form||!preview)return;for(const key of selected){const fieldName=key==='suggestedSlug'?'slug':key;const control=form.elements.namedItem(fieldName);if(!(control instanceof HTMLInputElement||control instanceof HTMLTextAreaElement||control instanceof HTMLSelectElement))continue;const value=preview[key];control.value=Array.isArray(value)?(key==='cast'||key==='crew'?value.join('\n'):value.join(', ')):String(value??'');control.dispatchEvent(new Event('input',{bubbles:true}));control.dispatchEvent(new Event('change',{bubbles:true}));}setMessage('Selected fields were copied into the editor. Review every value before saving.');}
  return <section className="tmdb-importer"><header><Database/><div><h2>TMDb metadata preview</h2><p>Fetch a preview, choose fields, then import. Existing values are not changed until you confirm.</p></div></header><div className="tmdb-lookup"><label>TMDb movie ID<input value={id} onChange={event=>setId(event.target.value.replace(/\D/g,''))} inputMode="numeric"/></label><button className="admin-primary" type="button" disabled={pending||!id} onClick={load}>{pending?<LoaderCircle className="spin"/>:<Database/>}Preview</button></div>{preview&&<><div className="tmdb-preview">{Object.entries(preview).filter(([,value])=>value!==undefined&&value!==''&&(!Array.isArray(value)||value.length)).map(([key,value])=><label key={key}><input type="checkbox" checked={selected.has(key)} onChange={event=>setSelected(current=>{const next=new Set(current);if(event.target.checked)next.add(key);else next.delete(key);return next;})}/><span><b>{labels[key]??key}</b><small>{Array.isArray(value)?value.join(', '):String(value)}</small></span></label>)}</div><button className="admin-primary" type="button" onClick={apply}><Check/>Import selected fields</button></>}{message&&<p>{message}</p>}<small>This product uses the TMDB API but is not endorsed or certified by TMDB.</small></section>;
}
