'use client';

import { Ban, CheckCircle2, CloudUpload, LoaderCircle, RotateCcw } from 'lucide-react';
import { useRef, useState } from 'react';

const csrf=()=>decodeURIComponent(document.cookie.split('; ').find((item)=>item.startsWith('cinerusubs_csrf='))?.split('=').slice(1).join('=')||'');
const mime=(file:File)=>file.type||({mkv:'video/x-matroska',m3u8:'application/vnd.apple.mpegurl'}[file.name.split('.').pop()?.toLocaleLowerCase()||'']||'application/octet-stream');
function put(url:string,body:Blob,headers:Record<string,string>,signal:AbortSignal,onProgress:(loaded:number)=>void){return new Promise<string>((resolve,reject)=>{const request=new XMLHttpRequest();request.open('PUT',url);for(const[key,value]of Object.entries(headers))request.setRequestHeader(key,value);request.upload.onprogress=event=>onProgress(event.loaded);request.onerror=()=>reject(new Error('R2 rejected the upload. Check bucket CORS and network access.'));request.onload=()=>request.status>=200&&request.status<300?resolve(request.getResponseHeader('ETag')||''):reject(new Error(`R2 rejected the upload (${request.status}).`));const abort=()=>{request.abort();reject(new DOMException('Upload cancelled.','AbortError'));};signal.addEventListener('abort',abort,{once:true});request.onloadend=()=>signal.removeEventListener('abort',abort);request.send(body);});}

export function UploadManager(){
  const input=useRef<HTMLInputElement>(null);const abortRef=useRef<AbortController|null>(null);const[kind,setKind]=useState('poster');const[pending,setPending]=useState(false);const[progress,setProgress]=useState('');const[percent,setPercent]=useState(0);const[error,setError]=useState('');
  async function upload(){const file=input.current?.files?.[0];if(!file)return;const controller=new AbortController();abortRef.current=controller;setPending(true);setError('');setPercent(0);setProgress('Requesting secure upload…');const auth={'Content-Type':'application/json','x-csrf-token':csrf()};const started=performance.now();let multipart:{assetId:string;uploadId:string}|null=null;const report=(loaded:number,total=file.size)=>{const elapsed=Math.max((performance.now()-started)/1000,.1);setPercent(Math.min(100,Math.round(loaded/total*100)));setProgress(`${Math.round(loaded/total*100)}% · ${(loaded/elapsed/1_000_000).toFixed(1)} MB/s`);};try{
    if(kind==='media'&&file.size>500_000_000){const start=await fetch('/api/admin/uploads/multipart/start',{method:'POST',headers:auth,body:JSON.stringify({kind,fileName:file.name,contentType:mime(file),size:file.size}),signal:controller.signal});const ticket=await start.json();if(!start.ok)throw new Error(ticket.error?.message||'Multipart upload could not start.');multipart=ticket;const parts:{ETag:string;PartNumber:number}[]=[];let uploaded=0;const partCount=Math.ceil(file.size/ticket.partSize);for(let index=0;index<partCount;index++){const partNumber=index+1;setProgress(`Signing part ${partNumber} of ${partCount}…`);const signature=await fetch(`/api/admin/uploads/multipart/${ticket.assetId}/part`,{method:'POST',headers:auth,body:JSON.stringify({uploadId:ticket.uploadId,partNumber}),signal:controller.signal});const signed=await signature.json();if(!signature.ok)throw new Error(signed.error?.message||`Part ${partNumber} could not be signed.`);const chunk=file.slice(index*ticket.partSize,Math.min(file.size,(index+1)*ticket.partSize));const etag=await put(signed.uploadUrl,chunk,{},controller.signal,loaded=>report(uploaded+loaded));if(!etag)throw new Error('R2 did not expose the ETag header. Add ETag to the bucket CORS exposeHeaders list.');parts.push({ETag:etag,PartNumber:partNumber});uploaded+=chunk.size;report(uploaded);}setProgress('Finalizing multipart upload…');const complete=await fetch(`/api/admin/uploads/multipart/${ticket.assetId}/complete`,{method:'POST',headers:auth,body:JSON.stringify({uploadId:ticket.uploadId,parts}),signal:controller.signal});const result=await complete.json();if(!complete.ok)throw new Error(result.error?.message||'Multipart upload could not be finalized.');setProgress(`Ready: ${result.asset.objectKey}`);
    }else{const signed=await fetch('/api/admin/uploads/presign',{method:'POST',headers:auth,body:JSON.stringify({kind,fileName:file.name,contentType:mime(file),size:file.size}),signal:controller.signal});const ticket=await signed.json();if(!signed.ok)throw new Error(ticket.error?.message||'Upload could not be signed.');await put(ticket.uploadUrl,file,ticket.headers,controller.signal,report);setProgress('Verifying the stored object…');const complete=await fetch(`/api/admin/uploads/${ticket.assetId}/complete`,{method:'POST',headers:{'x-csrf-token':csrf()},signal:controller.signal});const result=await complete.json();if(!complete.ok)throw new Error(result.error?.message||'Uploaded object could not be verified.');setPercent(100);setProgress(`Ready: ${result.asset.objectKey}`);}
    if(input.current)input.current.value='';
  }catch(cause){if(multipart){await fetch(`/api/admin/uploads/multipart/${multipart.assetId}`,{method:'DELETE',headers:auth,body:JSON.stringify({uploadId:multipart.uploadId})}).catch(()=>undefined);}setError(cause instanceof DOMException&&cause.name==='AbortError'?'Upload cancelled.':cause instanceof Error?cause.message:'Upload failed.');setProgress('');setPercent(0);}finally{abortRef.current=null;setPending(false);}}
  return <section className="upload-manager"><header><CloudUpload/><div><h2>Secure object upload</h2><p>Files upload directly to R2. Large media automatically uses resumable-size signed parts.</p></div></header><div><label>Asset type<select value={kind} disabled={pending} onChange={event=>setKind(event.target.value)}><option value="poster">Poster</option><option value="backdrop">Backdrop</option><option value="subtitle">Subtitle</option><option value="media">Full media</option><option value="avatar">Avatar</option><option value="other">Other</option></select></label><label>Choose file<input ref={input} type="file" disabled={pending}/></label><button className="admin-primary" type="button" disabled={pending} onClick={upload}>{pending?<LoaderCircle className="spin"/>:error?<RotateCcw/>:<CloudUpload/>}{error?'Retry':'Upload'}</button>{pending&&<button className="admin-danger" type="button" onClick={()=>abortRef.current?.abort()}><Ban/>Cancel</button>}</div>{progress&&<><div className="upload-meter"><i style={{width:`${percent}%`}}/></div><p className="upload-progress"><CheckCircle2/>{progress}</p></>}{error&&<p className="admin-form-error">{error}</p>}</section>;
}
