import { isValidObjectId } from 'mongoose';
import { z } from 'zod';
import { assertMutationRequest, requirePermission } from '@/lib/auth';
import { connectDb } from '@/lib/db';
import { apiError } from '@/lib/http';
import { AuditLog, Episode, MediaAsset, Movie, Subtitle, TranslatorProfile } from '@/models';

const schema=z.object({assetId:z.string(),contentType:z.enum(['movie','episode']),contentId:z.string(),translatorId:z.string().optional(),language:z.string().trim().min(2).max(80),languageCode:z.string().trim().min(2).max(12).toLowerCase(),releaseMatches:z.array(z.string().trim().min(1)).max(30),fps:z.number().positive().max(240).optional(),format:z.enum(['srt','ass','vtt','zip']),hearingImpaired:z.boolean().default(false),version:z.number().int().min(1).max(100).default(1)});
export async function POST(request:Request){try{const session=await requirePermission('subtitles.create');await assertMutationRequest(request,session);const input=schema.parse(await request.json());if(!isValidObjectId(input.assetId)||!isValidObjectId(input.contentId))throw Object.assign(new Error('Asset or content record was not found.'),{status:404,code:'NOT_FOUND'});await connectDb();const[asset,content]=await Promise.all([MediaAsset.findOne({_id:input.assetId,kind:'subtitle',status:'active',uploadedBy:session.user.id}),input.contentType==='movie'?Movie.findById(input.contentId):Episode.findById(input.contentId)]);if(!asset||!content)throw Object.assign(new Error('Active subtitle asset or content record was not found.'),{status:404,code:'NOT_FOUND'});const extension=String(asset.fileName).split('.').pop()?.toLocaleLowerCase();if(extension!==input.format)throw Object.assign(new Error('Selected subtitle format does not match the uploaded file.'),{status:422,code:'FORMAT_MISMATCH'});let translator;if(session.user.role==='translator')translator=await TranslatorProfile.findOne({user:session.user.id});else if(input.translatorId&&isValidObjectId(input.translatorId))translator=await TranslatorProfile.findById(input.translatorId);if(!translator)throw Object.assign(new Error('A translator profile must be linked before submitting subtitles.'),{status:422,code:'TRANSLATOR_REQUIRED'});const subtitle=await Subtitle.create({[input.contentType]:input.contentId,language:input.language,languageCode:input.languageCode,translator:translator._id,releaseMatches:input.releaseMatches,fps:input.fps,format:input.format,hearingImpaired:input.hearingImpaired,fileKey:asset.objectKey,fileName:asset.fileName,fileSize:asset.size,version:input.version,verified:false,status:'draft',uploadedBy:session.user.id});asset.linkedModel='Subtitle';asset.linkedId=subtitle._id;await asset.save();await AuditLog.create({actor:session.user.id,action:'subtitle.create',entity:'Subtitle',entityId:String(subtitle._id),metadata:{language:subtitle.language,format:subtitle.format,contentType:input.contentType,contentId:input.contentId}});return Response.json({id:String(subtitle._id),status:'draft'},{status:201});}catch(error){return apiError(error);}}
