import type { Metadata } from 'next';
import { Download, ExternalLink, Play, ShieldAlert, Star } from 'lucide-react';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import { ShareButton } from '@/components/movie/share-button';
import { TrailerDialog } from '@/components/movie/trailer-dialog';
import { WatchlistButton } from '@/components/movie/watchlist-button';
import { SubtitleCard } from '@/components/subtitle/subtitle-card';
import { mayDistributeFullMedia, rightsLabel } from '@/lib/rights';
import { siteUrl } from '@/lib/env';
import { getActiveMediaVersions, getMovieBySlug, getMovies, getSubtitlesForMovie } from '@/services/catalog';
import { currentUser } from '@/lib/auth';
import { CommunityPanel } from '@/components/community/community-panel';
import { DownloadOptions } from '@/components/movie/download-options';
import { SafeImage } from '@/components/ui/safe-image';
import { absoluteSiteUrl } from '@/lib/assets';

export const dynamic = 'force-dynamic';
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> {
  const { slug } = await params; const movie = await getMovieBySlug(slug); if (!movie) return {};
  return { title: `${movie.title} (${movie.year})`, description: movie.overview.slice(0,160), alternates: { canonical: `/movies/${movie.slug}` }, openGraph: { type: 'video.movie', title: movie.title, description: movie.overview, images: [movie.backdropUrl], url: `${siteUrl}/movies/${movie.slug}` } };
}

export default async function MovieDetailPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params; const movie = await getMovieBySlug(slug); if (!movie) notFound();
  const [subtitles, related, versions, user] = await Promise.all([getSubtitlesForMovie(movie.id), getMovies({ genre: movie.genres[0] }), getActiveMediaVersions(movie.id,'movie'), currentUser()]);
  const distributable = mayDistributeFullMedia(movie.rightsStatus) && versions.length > 0;
  const streamable = distributable && versions.some((version) => version.directAvailable);
  const director = movie.crew.find((credit) => credit.role?.toLowerCase().includes('director'));
  const jsonLd = { '@context':'https://schema.org','@type':'Movie', name:movie.title, alternateName:movie.originalTitle ?? movie.sinhalaTitle, dateCreated:String(movie.year), duration:`PT${movie.runtime}M`, description:movie.overview, image:absoluteSiteUrl(movie.posterUrl), genre:movie.genres, countryOfOrigin:movie.countries.map((name)=>({ '@type':'Country',name })), director:director?{ '@type':'Person',name:director.name }:undefined };
  return <><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(jsonLd).replaceAll('<','\\u003c')}}/><article className="detail-page">
    <header className="detail-hero"><div className="detail-backdrop"><SafeImage src={movie.backdropUrl} fallbackSrc="/media/fallback-backdrop.svg" alt="" fill priority sizes="100vw"/></div><div className="detail-hero-inner"><div className="detail-poster"><SafeImage src={movie.posterUrl} fallbackSrc="/media/fallback-poster.svg" alt={`${movie.title} poster`} fill priority sizes="260px"/></div><div className="detail-title"><nav aria-label="Breadcrumb"><Link href="/">Home</Link><span>/</span><Link href="/movies">Movies</Link><span>/</span><span>{movie.title}</span></nav><span className="detail-kicker">{movie.genres.join(' · ')}</span><h1>{movie.title}</h1>{movie.originalTitle && movie.originalTitle !== movie.title && <p className="original-title">{movie.originalTitle}</p>}{movie.sinhalaTitle && <p className="sinhala-title" lang="si">{movie.sinhalaTitle}</p>}<div className="detail-meta"><span>{movie.year}</span><i/><span>{movie.runtime} min</span><i/><span>{movie.ageRating}</span><i/><span>{movie.languages.join(', ')}</span><i/><span>{movie.releaseStatus}</span></div><div className="rating-row">{movie.imdbRating && <span><b>IMDb</b><strong><Star/>{movie.imdbRating.toFixed(1)}</strong></span>}{movie.tmdbRating && <span><b>TMDb</b><strong><Star/>{movie.tmdbRating.toFixed(1)}</strong></span>}<span className={`rights-chip rights-${movie.rightsStatus}`}>{rightsLabel(movie.rightsStatus)}</span></div><p className="detail-overview">{movie.overview}</p><div className="detail-actions">{movie.trailerUrl && <TrailerDialog title={movie.title} url={movie.trailerUrl}/>} {streamable && <Link className="action-button" href={`/watch/${versions[0]!.id}`}><Play/>Watch Online</Link>} {distributable && <DownloadOptions title={movie.title} posterUrl={movie.posterUrl} versions={versions}/>} {subtitles[0] && <a className="action-button subtitle-action" href={`/api/subtitles/${subtitles[0].id}/download`}><Download/>Download Sinhala Subtitle</a>}</div><div className="detail-secondary"><WatchlistButton id={movie.id} slug={movie.slug} title={movie.title} posterUrl={movie.posterUrl} label/><ShareButton title={movie.title}/></div></div></div></header>
    <nav className="detail-tabs" aria-label="Movie sections"><a href="#overview">Overview</a><a href="#subtitles">Subtitles <span>{subtitles.length}</span></a><a href="#media">Media</a><a href="#cast">Cast & Crew</a><a href="#reviews">Reviews</a><a href="#details">Details</a></nav>
    <div className="detail-content"><div className="detail-main"><section id="overview" className="detail-section"><span className="section-label">Story</span><h2>Overview</h2><p className="long-overview">{movie.overview}</p><div className="facts-grid"><div><span>Director</span><b>{director?.name ?? 'Not listed'}</b></div><div><span>Release date</span><b>{new Date(movie.releaseDate).toLocaleDateString('en-LK',{day:'numeric',month:'long',year:'numeric'})}</b></div><div><span>Countries</span><b>{movie.countries.join(', ')}</b></div><div><span>Languages</span><b>{movie.languages.join(', ')}</b></div><div><span>Genres</span><b>{movie.genres.join(', ')}</b></div><div><span>Runtime</span><b>{movie.runtime} minutes</b></div></div></section>
      <section id="subtitles" className="detail-section"><span className="section-label">Matched downloads</span><h2>Subtitles</h2>{subtitles.length ? <div className="subtitle-list">{subtitles.map((subtitle)=><SubtitleCard key={subtitle.id} subtitle={subtitle}/>)}</div> : <div className="inline-empty">No published subtitles are attached to this title.</div>}</section>
      <section id="media" className="detail-section"><span className="section-label">Available versions</span><h2>Downloads</h2>{distributable ? <><div className="media-version-list">{versions.map((version) => <div key={version.id}><span><b>{version.quality}</b><small>{version.releaseType} · {version.videoCodec ?? 'Video'} · {version.resolution}</small></span><em>{(version.fileSize/1_000_000_000).toFixed(1)} GB</em></div>)}</div><DownloadOptions title={movie.title} posterUrl={movie.posterUrl} versions={versions}/></> : <div className="rights-notice"><ShieldAlert/><div><b>Full media is not available from CineSeya.lk</b><p>{movie.rightsStatus === 'subtitle_only' || movie.rightsStatus === 'unavailable' ? 'This listing is limited to metadata, trailers, reviews, subtitles and legitimate external information.' : 'No verified distributable media version is active for this title.'}</p></div></div>}</section>
      <section id="cast" className="detail-section"><span className="section-label">People</span><h2>Cast & Crew</h2><div className="credits-grid">{[...movie.cast,...movie.crew].map((credit,index)=><Link href={`/person/${credit.slug}`} key={`${credit.slug}-${index}`}><span>{credit.name.split(' ').map((word)=>word[0]).join('').slice(0,2)}</span><b>{credit.name}</b><small>{credit.character ?? credit.role ?? 'Cast'}</small></Link>)}</div></section>
      <section id="reviews" className="detail-section"><span className="section-label">Community</span><h2>Reviews & Comments</h2><CommunityPanel type="movie" id={movie.id} authenticated={Boolean(user)}/></section>
    </div><aside className="detail-sidebar"><section id="details"><h2>Title details</h2><dl><div><dt>Original title</dt><dd>{movie.originalTitle ?? movie.title}</dd></div><div><dt>Year</dt><dd>{movie.year}</dd></div><div><dt>Age rating</dt><dd>{movie.ageRating}</dd></div><div><dt>Quality</dt><dd>{movie.qualities.join(', ') || 'Metadata only'}</dd></div><div><dt>Subtitle languages</dt><dd>{movie.subtitleLanguages.join(', ') || 'None attached'}</dd></div></dl></section><section><h2>External information</h2>{movie.imdbId && <a href={`https://www.imdb.com/title/${movie.imdbId}/`} target="_blank" rel="noreferrer">IMDb <ExternalLink/></a>}{movie.tmdbId && <a href={`https://www.themoviedb.org/movie/${movie.tmdbId}`} target="_blank" rel="noreferrer">TMDb <ExternalLink/></a>}<a href={`https://en.wikipedia.org/wiki/Special:Search?search=${encodeURIComponent(movie.title)}`} target="_blank" rel="noreferrer">Wikipedia <ExternalLink/></a></section><section className="rights-sidebar"><h2>Content access</h2><p>Rights status: <b>{rightsLabel(movie.rightsStatus)}</b></p><small>CineSeya.lk enables full media controls only for owned, licensed or public-domain files that an administrator has explicitly activated.</small></section></aside></div>
    {related.filter((item)=>item.id!==movie.id).length>0 && <section className="detail-related"><header><span>You may also like</span><h2>Related titles</h2></header><div className="catalog-grid compact-grid">{related.filter((item)=>item.id!==movie.id).slice(0,6).map((item)=><Link href={`/movies/${item.slug}`} key={item.id}><span><SafeImage src={item.posterUrl} fallbackSrc="/media/fallback-poster.svg" alt="" fill sizes="150px"/></span><b>{item.title}</b><small>{item.year}</small></Link>)}</div></section>}
  </article></>;
}
